# Generated by Django 2.2.10 on 2021-07-02 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
